const $=s=>document.querySelector(s);const app=$("#app");const chapters=window.ESTIMO_CHAPTERS||[];let currentChapter=localStorage.getItem("estimo_current_chapter")||(chapters[0]?.id||null);
const state={score:+(localStorage.getItem("estimo_score")||0),answered:+(localStorage.getItem("estimo_answered")||0),correct:+(localStorage.getItem("estimo_correct")||0),completedLessons:JSON.parse(localStorage.getItem("estimo_lessons")||"[]")};
function saveState(){localStorage.setItem("estimo_score",state.score);localStorage.setItem("estimo_answered",state.answered);localStorage.setItem("estimo_correct",state.correct);localStorage.setItem("estimo_lessons",JSON.stringify(state.completedLessons))}
function ch(){return chapters.find(x=>x.id===currentChapter)||chapters[0]}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function markLesson(id){if(!state.completedLessons.includes(id)){state.completedLessons.push(id);saveState()}}
function home(){const c=ch(),done=state.completedLessons.filter(x=>x.startsWith(c.id+":")).length,pct=Math.round(done/c.lessons.length*100);app.innerHTML=`
<section class="hero"><div class="kicker">App didattica modulare</div><h1>ESTIMO LAB</h1><p>${esc(c.title)}</p></section>
<div class="section-title"><h2>Capitoli</h2><small>struttura ampliabile</small></div>
<div class="chapter-row"><button class="chapter-chip active"><b>${esc(c.shortTitle)}</b><small>${esc(c.classLabel)}</small></button><button class="chapter-chip locked" disabled><b>+ Prossimo capitolo</b><small>pronto per essere aggiunto</small></button></div>
<div class="section-title"><h2>Come vuoi lavorare?</h2></div>
<div class="grid three">
<div class="card action-card"><div><div class="emoji">📖</div><h3>Impara</h3><p class="small">Studio per paragrafi brevi.</p></div><button class="primary" onclick="study()">Apri</button></div>
<div class="card action-card"><div><div class="emoji">🎯</div><h3>Allenati</h3><p class="small">Quiz, vero/falso e casi.</p></div><button class="primary" onclick="quizMenu()">Apri</button></div>
<div class="card action-card"><div><div class="emoji">🧮</div><h3>Calcola</h3><p class="small">Formule ed esercizi guidati.</p></div><button class="primary" onclick="calcMenu()">Apri</button></div>
<div class="card action-card"><div><div class="emoji">⚡</div><h3>Ripasso 5'</h3><p class="small">Gli 8 punti chiave.</p></div><button class="secondary" onclick="recap()">Ripassa</button></div>
<div class="card action-card"><div><div class="emoji">🏆</div><h3>Verifica</h3><p class="small">20 domande casuali.</p></div><button class="secondary" onclick="startFinal()">Inizia</button></div>
<div class="card action-card"><div><div class="emoji">📈</div><h3>Progressi</h3><p class="small">${pct}% lezioni completate.</p></div><button class="secondary" onclick="progress()">Vedi</button></div>
</div><div class="spacer"></div><div class="notice"><b>Espandibile:</b> i prossimi capitoli possono essere aggiunti mantenendo lo stesso link.</div>`}
function study(){const c=ch();app.innerHTML=`<div class="section-title"><h2>${esc(c.title)}</h2><small>Impara</small></div><div class="lesson-list">${c.lessons.map(l=>`<details class="lesson" ontoggle="if(this.open)markLesson('${c.id}:${l.id}')"><summary>${l.title}</summary><div class="lesson-content"><p class="small">${esc(l.summary||"")}</p>${l.html}</div></details>`).join("")}</div>`}
function quizMenu(){app.innerHTML=`<div class="section-title"><h2>Allenati</h2><small>${esc(ch().shortTitle)}</small></div><div class="grid three">
<div class="card action-card"><div><div class="emoji">🪪</div><h3>Quiz: fissa i concetti</h3><p class="small">10 domande per consolidare i concetti chiave.</p></div><button class="primary" onclick="startQuiz('quiz',10)">Inizia</button></div>
<div class="card action-card"><div><div class="emoji">✅</div><h3>Vero / Falso</h3><p class="small">10 domande rapide.</p></div><button class="primary" onclick="startQuiz('tf',10)">Inizia</button></div>
<div class="card action-card"><div><div class="emoji">🧭</div><h3>Quale criterio?</h3><p class="small">Casi pratici.</p></div><button class="primary" onclick="startQuiz('cases',6)">Inizia</button></div></div>`}
function startQuiz(type,n){const c=ch();let items=type==="quiz"?shuffle(c.quiz).slice(0,n):type==="tf"?shuffle(c.trueFalse).slice(0,n):shuffle(c.cases).slice(0,n);runQuiz(items,type,0,0)}
function runQuiz(items,type,i,score){if(i>=items.length){app.innerHTML=`<div class="card"><div class="kicker">Risultato</div><div class="bigscore">${score}/${items.length}</div><p>${score>=Math.ceil(items.length*.7)?"Buon lavoro.":"Conviene ripassare i punti sbagliati."}</p><button class="primary" onclick="quizMenu()">Torna agli allenamenti</button></div>`;return}const q=items[i],answers=type==="tf"?["Vero","Falso"]:q.a,pct=Math.round(i/items.length*100);app.innerHTML=`<div class="section-title"><h2>${type==="tf"?"Vero / Falso":type==="cases"?"Quale criterio?":"Quiz: fissa i concetti"}</h2><small>${i+1}/${items.length}</small></div><div class="progressbar"><span style="width:${pct}%"></span></div><div class="spacer"></div><div class="quiz-card"><div class="quiz-q">${esc(q.q)}</div><div class="answers">${answers.map((a,j)=>`<button class="answer" onclick="answerQuiz(${j})">${esc(a)}</button>`).join("")}</div><div id="feedback"></div></div>`;window.__items=items;window.__type=type;window.answerQuiz=function(idx){const ci=type==="tf"?(q.c?0:1):q.c;document.querySelectorAll(".answer").forEach((b,j)=>{b.disabled=true;if(j===ci)b.classList.add("correct");if(j===idx&&idx!==ci)b.classList.add("wrong")});const ok=idx===ci;state.answered++;if(ok){state.correct++;state.score+=10}saveState();$("#feedback").innerHTML=`<div class="feedback"><b>${ok?"Corretto.":"Non corretto."}</b><br>${esc(q.e||"")}</div><button class="primary" style="margin-top:12px" onclick="runQuiz(window.__items,window.__type,${i+1},${score+(ok?1:0)})">Continua</button>`}}
function recap(){app.innerHTML=`<div class="section-title"><h2>Ripasso in 5 minuti</h2><small>8 punti</small></div><div class="lesson-list">${ch().recap.map((x,i)=>`<div class="card"><b>${i+1}.</b> ${esc(x)}</div>`).join("")}</div>`}
function startFinal(){const c=ch(),pool=shuffle(c.quiz).slice(0,12).concat(shuffle(c.trueFalse).slice(0,4)).concat(shuffle(c.cases).slice(0,4));const mixed=shuffle(pool.map(x=>typeof x.c==="boolean"?{q:x.q,a:["Vero","Falso"],c:x.c?0:1,e:x.e}:x));runQuiz(mixed,"quiz",0,0)}
function calcMenu(){app.innerHTML=`<div class="section-title"><h2>Calcola</h2><small>Formule del capitolo</small></div><div class="calc-grid">
<div class="card calc-form"><h3>Comparazione</h3><span class="formula">Vx = (ΣV / Σp) · px</span><label>ΣV (€)</label><input id="sumV" type="number" value="630000"><label>Σp</label><input id="sumP" type="number" value="300"><label>px</label><input id="px" type="number" value="95"><button class="primary" style="margin-top:12px" onclick="calcComparison()">Calcola</button><div id="r1"></div></div>
<div class="card calc-form"><h3>Capitalizzazione</h3><span class="formula">V₀ = Bf / r</span><label>Bf annuo (€)</label><input id="bf" type="number" value="6000"><label>r (%)</label><input id="r" type="number" value="3" step="0.1"><button class="primary" style="margin-top:12px" onclick="calcCap()">Calcola</button><div id="r2"></div></div>
<div class="card calc-form"><h3>Trasformazione</h3><span class="formula">Vt = Vm − K</span><label>Vm (€)</label><input id="vm" type="number" value="250000"><label>K (€)</label><input id="k" type="number" value="90000"><button class="primary" style="margin-top:12px" onclick="calcTrans()">Calcola</button><div id="r3"></div></div>
<div class="card calc-form"><h3>Complementare</h3><span class="formula">VA = V − VB</span><label>V (€)</label><input id="v" type="number" value="400000"><label>VB (€)</label><input id="vb" type="number" value="310000"><button class="primary" style="margin-top:12px" onclick="calcComp()">Calcola</button><div id="r4"></div></div></div>`}
function fmt(n){return new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(n)}function calcComparison(){let a=+$("#sumV").value,b=+$("#sumP").value,p=+$("#px").value;$("#r1").innerHTML=`<div class="result">${fmt(a)} / ${b} = ${fmt(a/b)}<br><b>Vx = ${fmt((a/b)*p)}</b></div>`}function calcCap(){let bf=+$("#bf").value,r=+$("#r").value/100;$("#r2").innerHTML=`<div class="result"><b>V₀ = ${fmt(bf/r)}</b></div>`}function calcTrans(){let vm=+$("#vm").value,k=+$("#k").value;$("#r3").innerHTML=`<div class="result"><b>Vt = ${fmt(vm-k)}</b></div>`}function calcComp(){let v=+$("#v").value,vb=+$("#vb").value;$("#r4").innerHTML=`<div class="result"><b>VA = ${fmt(v-vb)}</b></div>`}
function progress(){const c=ch(),done=state.completedLessons.filter(x=>x.startsWith(c.id+":")).length,acc=state.answered?Math.round(state.correct/state.answered*100):0;app.innerHTML=`<div class="section-title"><h2>Progressi</h2><small>salvati sul dispositivo</small></div><div class="stats"><div class="stat"><b>${done}/${c.lessons.length}</b><span>lezioni</span></div><div class="stat"><b>${state.answered}</b><span>risposte</span></div><div class="stat"><b>${acc}%</b><span>corrette</span></div></div><div class="card" style="margin-top:12px"><h3>Punti</h3><div class="bigscore">${state.score}</div></div>`}
document.querySelectorAll("[data-nav]").forEach(b=>b.addEventListener("click",()=>{const n=b.dataset.nav;if(n==="home")home();if(n==="study")study();if(n==="quiz")quizMenu();if(n==="calc")calcMenu();if(n==="progress")progress()}));$("#homeBtn").addEventListener("click",home);if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));home();